services:
  App\EventListeners\ReservationListener:
    class: App\EventListeners\ReservationListener
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }